
#cloud-config

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false
users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - REPLACE_ME_WITH_YOUR_SSH_KEY


packages:
  - git
  - golang
  - awscli
  - unzip
  - curl
  - net-tools
  - socat

write_files:
  - path: /etc/profile.d/golang.sh
    content: |
      export GOPATH=$HOME/go
      export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
    permissions: '0755'

runcmd:
  - mkdir -p /home/ubuntu/go/src/app
  - chown -R ubuntu:ubuntu /home/ubuntu/go
  - echo "Cloud-init finished" > /var/log/cloud-init-done